#define SECRET_WIFI_HOME_SSID "YOUR-HOME-WIFI"
#define  SECRET_WIFI_HOME_KEY "YOUR-WIFI-PASSKEY"

#define  SECRET_WIFI_INVERTER_SSID "AP_12345678"
#define  SECRET_WIFI_INVERTER_KEY "12345678"

#define  SECRET_WIFI_RELAIS_SSID "EM_12345678"
#define  SECRET_WIFI_RELAIS_KEY "check-sticker"

#define  SECRET_MQTT_BROKER_HOST "BROKER-IP-or-Hostname"
#define  SECRET_MQTT_BROKER_PORT 1883
#define  SECRET_MQTT_BROKER_USER "Client-USER"
#define  SECRET_MQTT_BROKER_PWD "Client-PWD"
#define  SECRET_MQTT_BROKER_MAINTOPIC "stats/energy/deye/"

#define  SECRET_INVERTER_WEBACCESS_USER "admin"
#define  SECRET_INVERTER_WEBACCESS_PWD "admin"

#define  SECRET_RELAIS_WEBACCESS_USER "check-Sticker"
#define  SECRET_RELAIS_WEBACCESS_PWD "check-sticker"
